import { Bebas_Neue } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";


const Bebas = Bebas_Neue({
  weight: '400',
  subsets: ['latin'],

});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Bebas.className}  h-[100vh]`}>
        <main className="p-1">{children}</main>
        <nav className="ml-4 mr-3 mt-3">
          <Nav />
        </nav>
      </body>
    </html>
  );
}
