import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import CartProvider from "./context/global_context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (

    <CartProvider>

      <html lang="en" className="">
        <body className={`${inter.className}  h-[100vh]  overscroll-contain overflow-scroll relative `}>
          <main className="p-1 ">{children}</main>
          <nav className="ml-4 mr-3 mt-3 sticky bottom-4">
            <Nav />
          </nav>
        </body>
      </html>

    </CartProvider>
  );
}
